title: Genshin Impact Блог
baseURL: /
params:
  palette: yellow
  header:
    title: Genshin Blog
    tagline: 'Гайды, персонажи, прохождения Genshin Impact'
    logo_img: images/logo.svg
    logo_img_alt: Genshin Logo
    background_img: images/oval-avocado.jpg
    has_nav: true
    nav_links:
      - label: Главная
        url: /
        style: link
      - label: Обо мне
        url: /about
        style: link
      - label: Связаться со мной
        url: /contact
        style: link
      - label: Гайды
        url: /assets/guides/
        style: link
        icon_class: dev
        new_window: false
        no_follow: false
        type: action
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: linkedin
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
  footer: {}
  domain: 'https://genshimp-03180.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
